import type { Prisma, QuoteWorkflowStage } from "../generated/prisma/client.ts";
import { confirmNoArtworkAction, createProductionJobAction, createPurchaseDraftsAction, markRequirementsReadyAction, readyProofAction, requestArtworkRevisionAction, resolveArtworkRevisionAction, resolveSupplierRequirementsAction, transitionWorkflowAction, uploadProofAction } from "../admin/operations-actions.ts";
import { workflowTransitions } from "../operations/workflow.ts";
import { StatusBadge } from "./admin-ui.tsx";

type OperationsQuote = Prisma.QuoteGetPayload<{ include: { lines: { include: { decorations: true } }; artworkFiles: true; workflowEvents: { include: { staffUser: { select: { name: true } } } }; revisionRequests: true; artworkProofs: { include: { decoration: { select: { locationLabel: true } } } }; productionJob: true; supplierRequirements: true; purchaseDrafts: true } }>;
export function QuoteOperations({ quote, writable }: { quote: OperationsQuote; writable: boolean }) {
  const next = workflowTransitions[quote.workflowStage as QuoteWorkflowStage];
  return <section className="admin-section"><h2>Quote-to-production workflow</h2><div className="admin-card"><StatusBadge value={quote.workflowStage}/>{writable && next.length > 0 && <form action={transitionWorkflowAction.bind(null, quote.id)} className="admin-inline"><select name="stage">{next.map((stage) => <option key={stage}>{stage}</option>)}</select><input name="note" placeholder="Optional transition note" maxLength={1000}/><button>Move stage</button></form>}</div>
    <ol className="admin-timeline">{quote.workflowEvents.map((event) => <li key={event.id}><strong>{event.newStage.replaceAll("_", " ")}</strong><span>{event.note ?? ""}</span><small>{event.staffUser?.name ?? "System"} · {event.createdAt.toLocaleString("en-NZ")}</small></li>)}</ol>
    <div className="admin-two-column"><article className="admin-card"><h3>Artwork revisions</h3>{quote.revisionRequests.map((revision) => <div key={revision.id}><StatusBadge value={revision.status}/><p>{revision.request}</p>{writable && revision.status === "OPEN" && <form action={resolveArtworkRevisionAction.bind(null, quote.id, revision.id)}><button>Resolve</button></form>}</div>)}{writable && <><form action={requestArtworkRevisionAction.bind(null, quote.id)}><select name="quoteLineId"><option value="">Whole quote</option>{quote.lines.map((line) => <option value={line.id} key={line.id}>{line.productNameSnapshot}</option>)}</select><textarea name="request" required maxLength={2000} placeholder="Revision instructions"/><button>Request revision</button></form>{quote.artworkFiles.length === 0 && <form action={confirmNoArtworkAction.bind(null, quote.id)}><input name="note" required placeholder="Reason no file is required"/><button>Confirm no artwork file required</button></form>}</>}</article>
      <article className="admin-card"><h3>Proofs</h3>{quote.artworkProofs.map((proof) => <div key={proof.id}><p>v{proof.version}: {proof.decoration.locationLabel} — <StatusBadge value={proof.status}/></p>{writable && proof.status === "DRAFT" && <form action={readyProofAction.bind(null, quote.id, proof.id)}><button>Make ready and create secure link</button></form>}</div>)}{writable && <form action={uploadProofAction.bind(null, quote.id)}><select name="quoteLineId" required>{quote.lines.map((line) => <option value={line.id} key={line.id}>{line.productNameSnapshot}</option>)}</select><select name="decorationId" required>{quote.lines.flatMap((line) => line.decorations.map((decoration) => <option value={decoration.id} key={decoration.id}>{line.productNameSnapshot}: {decoration.locationLabel}</option>))}</select><input type="file" name="file" accept="image/png,image/jpeg,application/pdf" required/><textarea name="note" maxLength={2000} placeholder="Internal proof note"/><button>Upload proof</button></form>}</article></div>
    <div className="admin-two-column"><article className="admin-card"><h3>Production</h3>{quote.productionJob ? <p><a href={`/admin/production/${quote.productionJob.jobNumber}`}>{quote.productionJob.jobNumber}</a> · <StatusBadge value={quote.productionJob.status}/></p> : writable && <form action={createProductionJobAction.bind(null, quote.id)}><button>Create production job</button></form>}</article><article className="admin-card"><h3>Supplier preparation</h3><p>{quote.supplierRequirements.length} requirements · {quote.purchaseDrafts.length} internal purchase drafts</p>{writable && <><form action={resolveSupplierRequirementsAction.bind(null, quote.id)}><button>Resolve current supplier sources</button></form><form action={markRequirementsReadyAction.bind(null, quote.id)}><button>Mark resolved lines ready to order</button></form><form action={createPurchaseDraftsAction.bind(null, quote.id)}><button>Create internal purchase drafts</button></form></>}</article></div>
  </section>;
}
