import "server-only";
import type { ProductionJobStatus, ProductionTaskStatus, StaffRole } from "../generated/prisma/client.ts";
import { database } from "../lib/database.ts";

export const taskTransitions: Record<ProductionTaskStatus, readonly ProductionTaskStatus[]> = { PENDING: ["READY", "ON_HOLD"], READY: ["IN_PROGRESS", "ON_HOLD"], IN_PROGRESS: ["COMPLETED", "ON_HOLD"], COMPLETED: [], ON_HOLD: ["READY", "IN_PROGRESS"] };
export const jobTransitions: Record<ProductionJobStatus, readonly ProductionJobStatus[]> = { PLANNING: ["READY", "ON_HOLD", "CANCELLED"], READY: ["IN_PROGRESS", "ON_HOLD", "CANCELLED"], IN_PROGRESS: ["ON_HOLD", "COMPLETED", "CANCELLED"], ON_HOLD: ["READY", "IN_PROGRESS", "CANCELLED"], COMPLETED: [], CANCELLED: [] };
export function mayViewSupplierCost(role: StaffRole) { return role === "ADMIN" || role === "CATALOGUE_MANAGER"; }
export function stockStale(updatedAt: Date | null, now = new Date(), thresholdMinutes = Number(process.env.CXA_STOCK_STALE_MINUTES ?? 120)) { return !updatedAt || now.getTime() - updatedAt.getTime() > thresholdMinutes * 60_000; }
export function operationalOverdue(requiredBy: Date | null, status: ProductionJobStatus, now = new Date()) { return Boolean(requiredBy && !["COMPLETED", "CANCELLED"].includes(status) && requiredBy.getTime() < new Date(now.toISOString().slice(0, 10)).getTime()); }

export async function updateProductionJob(jobId: string, staffUserId: string, input: { assignedToStaffUserId?: string | null; priority?: "LOW" | "NORMAL" | "HIGH" | "URGENT"; requiredBy?: Date | null; status?: ProductionJobStatus }) {
  const job = await database.productionJob.findUniqueOrThrow({ where: { id: jobId }, include: { items: { include: { tasks: true } }, quote: { include: { artworkFiles: true, artworkProofs: { where: { status: { not: "SUPERSEDED" } } }, supplierRequirements: true } } } });
  if (input.assignedToStaffUserId) { const staff = await database.staffUser.findFirst({ where: { id: input.assignedToStaffUserId, active: true } }); if (!staff) throw new Error("Assigned staff member is unavailable."); }
  if (input.status && !jobTransitions[job.status].includes(input.status)) throw new Error("That production job transition is not allowed.");
  if (input.status === "COMPLETED") { const tasks = job.items.flatMap((item) => item.tasks); const reasons = [tasks.some((task) => task.status !== "COMPLETED") ? "All decoration tasks must be completed." : null, job.quote.supplierRequirements.some((r) => !["READY_TO_ORDER", "ORDERED", "RECEIVED", "CANCELLED"].includes(r.status)) ? "Supplier requirements remain unresolved." : null, job.quote.artworkFiles.some((file) => !["APPROVED", "ARCHIVED", "DELETED"].includes(file.status)) ? "Artwork approval is incomplete." : null, job.quote.artworkProofs.some((proof) => proof.status !== "APPROVED") ? "Proof approval is incomplete." : null].filter(Boolean); if (reasons.length) throw new Error(reasons.join(" ")); }
  const changed = input.status ? "PRODUCTION_STATUS_CHANGED" : input.priority ? "PRODUCTION_PRIORITY_CHANGED" : input.requiredBy !== undefined ? "PRODUCTION_DUE_DATE_CHANGED" : "PRODUCTION_ASSIGNMENT_CHANGED";
  return database.$transaction(async (tx) => { const updated = await tx.productionJob.update({ where: { id: jobId }, data: { ...input, completedAt: input.status === "COMPLETED" ? new Date() : undefined } }); await tx.productionJobEvent.create({ data: { productionJobId: jobId, staffUserId, eventType: changed, summary: `${changed.replaceAll("_", " ")} by authorized staff.` } }); await tx.adminAuditLog.create({ data: { staffUserId, action: changed, entityType: "ProductionJob", entityId: jobId, summary: `${changed.replaceAll("_", " ")} for ${job.jobNumber}` } }); return updated; });
}

export async function updateProductionTask(jobId: string, taskId: string, staffUserId: string, status: ProductionTaskStatus, assignedToStaffUserId?: string | null) {
  const task = await database.productionDecorationTask.findFirst({ where: { id: taskId, productionJobItem: { productionJobId: jobId } } });
  if (!task) throw new Error("Production task not found for this job.");
  if (status !== task.status && !taskTransitions[task.status].includes(status)) throw new Error("That task transition is not allowed.");
  if (assignedToStaffUserId && !await database.staffUser.findFirst({ where: { id: assignedToStaffUserId, active: true } })) throw new Error("Assigned staff member is unavailable.");
  await database.$transaction(async (tx) => { await tx.productionDecorationTask.update({ where: { id: task.id }, data: { status, assignedToStaffUserId } }); await tx.productionJobEvent.create({ data: { productionJobId: jobId, staffUserId, eventType: "TASK_STATUS", summary: `${task.locationSnapshot} / ${task.methodSnapshot}: ${task.status} to ${status}` } }); await tx.adminAuditLog.create({ data: { staffUserId, action: "PRODUCTION_TASK_STATUS_CHANGED", entityType: "ProductionDecorationTask", entityId: task.id, summary: `${task.status} to ${status}` } }); });
}

export async function validatePurchaseDraft(draftId: string, staffUserId: string, confirmStale?: string) {
  const draft = await database.supplierPurchaseDraft.findUniqueOrThrow({ where: { id: draftId }, include: { items: { include: { supplierRequirement: { include: { supplierVariant: true } } } } } });
  const invalid = draft.items.filter((item) => !item.skuSnapshot || item.quantity < 1 || !item.supplierRequirement.supplierId || !item.supplierRequirement.supplierVariant?.active);
  if (!draft.items.length || invalid.length) throw new Error("Every purchase draft line requires a current supplier, exact active SKU, and positive quantity.");
  const stale = draft.items.some((item) => stockStale(item.supplierRequirement.supplierVariant?.stockUpdatedAt ?? null));
  if (stale && !confirmStale?.trim()) throw new Error("Stock data is stale. Explicit staff confirmation is required.");
  return database.$transaction(async (tx) => { const updated = await tx.supplierPurchaseDraft.update({ where: { id: draftId }, data: { status: "READY", ...(stale ? { staleStockConfirmedAt: new Date(), staleStockConfirmedById: staffUserId, staleStockConfirmationNote: confirmStale!.replace(/[<>]/g, "").slice(0, 500) } : {}) } }); await tx.adminAuditLog.create({ data: { staffUserId, action: "PURCHASE_DRAFT_READY", entityType: "SupplierPurchaseDraft", entityId: draftId, summary: `${draft.draftNumber} marked ready for ordering` } }); return updated; });
}

export async function quoteOperationalExceptions(quoteId: string) { const quote = await database.quote.findUniqueOrThrow({ where: { id: quoteId }, include: { artworkFiles: true, artworkProofs: { where: { status: { not: "SUPERSEDED" } } }, supplierRequirements: { include: { supplierVariant: true } }, productionJob: true, purchaseDrafts: true } }); const warnings: string[] = []; if (quote.artworkFiles.some((x) => x.status === "UPLOADED")) warnings.push("Artwork awaiting review"); if (quote.artworkFiles.some((x) => x.status === "REJECTED")) warnings.push("Artwork rejected"); if (quote.artworkProofs.some((x) => x.status === "READY_FOR_CUSTOMER")) warnings.push("Proof awaiting customer"); if (quote.artworkProofs.some((x) => x.status === "REJECTED")) warnings.push("Proof rejected"); if (quote.supplierRequirements.some((x) => !x.supplierVariantId)) warnings.push("Supplier mapping unresolved"); if (quote.supplierRequirements.some((x) => stockStale(x.supplierVariant?.stockUpdatedAt ?? null))) warnings.push("Supplier stock stale"); if (!quote.productionJob && ["PRODUCTION_PLANNING", "SUPPLIER_ORDER_PREPARATION", "READY_FOR_PRODUCTION"].includes(quote.workflowStage)) warnings.push("Production job not created"); if (quote.purchaseDrafts.some((x) => x.status === "DRAFT")) warnings.push("Purchase draft incomplete"); return warnings; }
