import { randomUUID, createHash } from "node:crypto";
import { assertSafeDevelopmentDatabase, loadLocalEnvironment } from "./development-database.ts";
loadLocalEnvironment(); assertSafeDevelopmentDatabase();
const { database } = await import("../src/lib/database.ts"); const { artworkStorage } = await import("../src/artwork/storage.ts"); const { submitQuoteRequest } = await import("../src/quotes/submission.ts"); const { getPublishedProductBySlug } = await import("../src/catalogue/customer.ts");
const idempotencyKey = "12000000-0000-4000-8000-000000000012";
try {
  const existing = await database.quote.findUnique({ where: { idempotencyKey }, include: { artworkFiles: { select: { originalFileName: true, status: true, scanStatus: true } } } });
  if (existing) { console.log(JSON.stringify({ quoteNumber: existing.quoteNumber, artwork: existing.artworkFiles }, null, 2)); }
  else {
    const product = await getPublishedProductBySlug("101cvc-american-apparel-cvc-womens-racerneck-tank"); if (!product) throw new Error("Development product is unavailable."); const colour = product.colours.find((item) => item.description.toLowerCase().includes("black") && item.variants.some((variant) => variant.availability !== "OUT_OF_STOCK")); const variant = colour?.variants.find((item) => item.availability !== "OUT_OF_STOCK"); if (!colour || !variant) throw new Error("Black development variant is unavailable.");
    const lineId = `task12-${randomUUID()}`; const files = [{ bytes: Uint8Array.from([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82]), extension: "png", mimeType: "image/png", name: "task12-left-chest.png", location: "FRONT_LEFT_CHEST", method: "DTF" }, { bytes: new TextEncoder().encode("%PDF-1.4\n% CXA harmless development artwork\n%%EOF\n"), extension: "pdf", mimeType: "application/pdf", name: "task12-full-back.pdf", location: "BACK_FULL", method: "SCREEN_PRINT" }] as const;
    const artwork = [];
    for (const file of files) { const token = randomUUID(); const storageKey = await artworkStorage.save(file.bytes, file.extension); await database.temporaryArtworkUpload.create({ data: { clientUploadToken: token, quoteLineClientId: lineId, decorationLocation: file.location, originalFileName: file.name, storageKey, mimeType: file.mimeType, extension: file.extension, sizeBytes: file.bytes.length, sha256: createHash("sha256").update(file.bytes).digest("hex"), expiresAt: new Date(Date.now() + 60 * 60 * 1000) } }); artwork.push({ location: file.location, method: file.method, artwork: { token, originalFileName: file.name, mimeType: file.mimeType, sizeBytes: file.bytes.length, status: "UPLOADED" as const } }); }
    const result = await submitQuoteRequest({ customer: { customerName: "CXA Artwork Development Test", businessName: "CXA Development", email: "artwork-development@example.invalid", phone: "", requiredBy: "", deliveryMethod: "PICKUP", deliveryAddress: "", customerNotes: "Harmless Task 12 artwork workflow verification." }, lines: [{ quoteLineId: lineId, productId: product.id, productSlug: product.slug, productName: product.name, colourCode: colour.code, colourDescription: colour.description, productImage: colour.images[0] ?? product.primaryImage, sizeQuantities: { [variant.size]: 2 }, totalGarmentQuantity: 2, decorations: artwork }], idempotencyKey, website: "", startedAt: Date.now() - 2000 }, { notifier: async () => ({ staff: "skipped", customer: "skipped" }) }); if (!result.ok) throw new Error(result.errors.join(" "));
    const stored = await database.quote.findUniqueOrThrow({ where: { idempotencyKey }, include: { artworkFiles: { select: { originalFileName: true, status: true, scanStatus: true, decoration: { select: { locationLabel: true, methodLabel: true } } } } } }); console.log(JSON.stringify({ quoteNumber: stored.quoteNumber, product: product.name, colour: colour.description, artwork: stored.artworkFiles }, null, 2));
  }
} finally { await database.$disconnect(); }
