import { assertSafeDevelopmentDatabase, loadLocalEnvironment } from "./development-database.ts";
loadLocalEnvironment(); assertSafeDevelopmentDatabase();
const { database } = await import("../src/lib/database.ts");
const { sendProofToCustomer } = await import("../src/operations/proof-delivery.ts");
const { readyProofForCustomer, respondToProof, revokeProofTokens } = await import("../src/operations/proofs.ts");
const { updateProductionJob, updateProductionTask, validatePurchaseDraft, stockStale } = await import("../src/operations/hardening.ts");
const staff = await database.staffUser.findFirstOrThrow({ where: { active: true, role: "ADMIN" } });
const quote = await database.quote.findUniqueOrThrow({ where: { quoteNumber: "CXA-2026-00062" }, include: { artworkProofs: true, productionJob: { include: { items: { include: { tasks: true } } } }, purchaseDrafts: true } });
if (!quote.productionJob) throw new Error("Development production job is missing.");
await updateProductionJob(quote.productionJob.id, staff.id, { assignedToStaffUserId: staff.id });
await updateProductionJob(quote.productionJob.id, staff.id, { priority: "HIGH" });
await updateProductionJob(quote.productionJob.id, staff.id, { requiredBy: new Date("2026-09-15T00:00:00Z") });
for (const item of quote.productionJob.items) for (const task of item.tasks) await updateProductionTask(quote.productionJob.id, task.id, staff.id, task.status, staff.id);
const proof = quote.artworkProofs[0]; if (!proof) throw new Error("Development proof is missing.");
const first = await readyProofForCustomer(proof.id, staff.id, 1); await revokeProofTokens(proof.id, staff.id); const revokedWorks = await respondToProof(first.token, "APPROVED");
await sendProofToCustomer(proof.id, staff.id, { simulate: true });
const regenerated = await readyProofForCustomer(proof.id, staff.id, 1); const regeneratedWorks = await respondToProof(regenerated.token, "APPROVED", "Task 14 safe development approval.");
for (const draft of quote.purchaseDrafts) if (draft.status === "DRAFT") await validatePurchaseDraft(draft.id, staff.id, "Stored stock age reviewed during controlled Task 14 development verification.");
const state = await database.productionJob.findUniqueOrThrow({ where: { id: quote.productionJob.id }, include: { items: { include: { tasks: true } }, quote: { include: { supplierRequirements: { include: { supplierVariant: true } } } } } });
console.log(JSON.stringify({ quoteNumber: quote.quoteNumber, jobNumber: state.jobNumber, assignedTo: staff.name, priority: state.priority, internalDueDate: state.requiredBy?.toISOString().slice(0, 10), tasks: state.items.flatMap((item) => item.tasks).map((task) => ({ location: task.locationSnapshot, status: task.status, assigned: Boolean(task.assignedToStaffUserId) })), revokedTokenAccepted: revokedWorks, regeneratedTokenAccepted: regeneratedWorks, proofNotificationMode: "SIMULATED", supplierOrderSubmitted: false, staleRequirements: state.quote.supplierRequirements.filter((r) => stockStale(r.supplierVariant?.stockUpdatedAt ?? null)).length }, null, 2));
await database.$disconnect();
