"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { database } from "../lib/database.ts";
import { sendProofToCustomer } from "../operations/proof-delivery.ts";
import { readyProofForCustomer, revokeProofTokens } from "../operations/proofs.ts";
import { updateProductionJob, updateProductionTask, validatePurchaseDraft } from "../operations/hardening.ts";
import { requireStaff } from "./session.ts";
const id = z.string().cuid();
export async function sendProofAction(quoteId: string, proofId: string) { const staff = await requireStaff("quotes:write"); const proof = await database.artworkProof.findFirst({ where: { id: id.parse(proofId), quoteId: id.parse(quoteId) } }); if (!proof) throw new Error("Proof not found for this quote."); await sendProofToCustomer(proof.id, staff.id); revalidatePath(`/admin/quotes/${(await database.quote.findUniqueOrThrow({ where: { id: quoteId } })).quoteNumber}`); }
export async function revokeProofAction(quoteId: string, proofId: string) { const staff = await requireStaff("quotes:write"); const proof = await database.artworkProof.findFirst({ where: { id: id.parse(proofId), quoteId: id.parse(quoteId) } }); if (!proof) throw new Error("Proof not found for this quote."); await revokeProofTokens(proof.id, staff.id); revalidatePath("/admin/proofs"); }
export async function regenerateProofAction(quoteId: string, proofId: string) { const staff = await requireStaff("quotes:write"); const proof = await database.artworkProof.findFirst({ where: { id: id.parse(proofId), quoteId: id.parse(quoteId) } }); if (!proof) throw new Error("Proof not found for this quote."); await revokeProofTokens(proof.id, staff.id); await readyProofForCustomer(proof.id, staff.id); await database.adminAuditLog.create({ data: { staffUserId: staff.id, action: "PROOF_TOKEN_REGENERATED", entityType: "ArtworkProof", entityId: proof.id, summary: "Proof link regenerated; plaintext token not logged" } }); revalidatePath("/admin/proofs"); }
export async function updateJobAction(jobId: string, formData: FormData) { const staff = await requireStaff("quotes:write"); const job = await database.productionJob.findUniqueOrThrow({ where: { id: id.parse(jobId) } }); const mode = String(formData.get("mode")); if (mode === "assignment") await updateProductionJob(job.id, staff.id, { assignedToStaffUserId: String(formData.get("staffId") || "") || null }); else if (mode === "priority") await updateProductionJob(job.id, staff.id, { priority: z.enum(["LOW", "NORMAL", "HIGH", "URGENT"]).parse(formData.get("priority")) }); else if (mode === "due") { const value = String(formData.get("requiredBy") || ""); await updateProductionJob(job.id, staff.id, { requiredBy: value ? new Date(`${value}T00:00:00Z`) : null }); } else await updateProductionJob(job.id, staff.id, { status: z.enum(["PLANNING", "READY", "IN_PROGRESS", "ON_HOLD", "COMPLETED", "CANCELLED"]).parse(formData.get("status")) }); revalidatePath(`/admin/production/${job.jobNumber}`); revalidatePath("/admin/production"); }
export async function updateTaskAction(jobId: string, taskId: string, formData: FormData) { const staff = await requireStaff("quotes:write"); await updateProductionTask(id.parse(jobId), id.parse(taskId), staff.id, z.enum(["PENDING", "READY", "IN_PROGRESS", "COMPLETED", "ON_HOLD"]).parse(formData.get("status")), String(formData.get("staffId") || "") || null); const job = await database.productionJob.findUniqueOrThrow({ where: { id: jobId } }); revalidatePath(`/admin/production/${job.jobNumber}`); }
export async function readyPurchaseDraftAction(draftId: string, formData: FormData) { const staff = await requireStaff("suppliers:write"); const draft = await validatePurchaseDraft(id.parse(draftId), staff.id, String(formData.get("staleConfirmation") || "") || undefined); revalidatePath(`/admin/purchase-orders/${draft.draftNumber}`); }
export async function updateNotificationSettingsAction(formData: FormData) { const staff = await requireStaff("admin:read"); if (staff.role !== "ADMIN") throw new Error("Only administrators can update notification policy."); const enabled = (name: string) => formData.get(name) === "on"; const data = { sendCustomerAcknowledgement: enabled("sendCustomerAcknowledgement"), sendStaffQuoteNotification: enabled("sendStaffQuoteNotification"), sendProofReady: enabled("sendProofReady"), sendArtworkRevision: enabled("sendArtworkRevision"), sendInProduction: enabled("sendInProduction"), sendReady: enabled("sendReady") }; await database.notificationSettings.upsert({ where: { id: "default" }, create: data, update: data }); revalidatePath("/admin/settings"); }
