import "server-only";
import { createHmac, randomUUID } from "node:crypto";
import type { RateLimitScope } from "../generated/prisma/client.ts";
import { database } from "../lib/database.ts";
const policies: Record<RateLimitScope, { limit: number; windowMs: number }> = { LOGIN: { limit: 8, windowMs: 900_000 }, QUOTE_SUBMISSION: { limit: 8, windowMs: 600_000 }, ARTWORK_UPLOAD: { limit: 12, windowMs: 900_000 }, PROOF_ACCESS: { limit: 30, windowMs: 60_000 }, PROOF_ACTION: { limit: 8, windowMs: 600_000 } };
function secret() { const value = process.env.CXA_RATE_LIMIT_SECRET ?? (process.env.NODE_ENV === "production" ? "" : "cxa-development-rate-limit-secret"); if (!value) throw new Error("CXA_RATE_LIMIT_SECRET is required in production."); return value; }
export function rateLimitKeyHash(scope: RateLimitScope, identifier: string) { return createHmac("sha256", secret()).update(`${scope}:${identifier.trim().toLowerCase().slice(0, 500)}`).digest("hex"); }
export async function consumeRateLimit(scope: RateLimitScope, identifier: string, now = new Date()) { const policy = policies[scope]; const windowStart = new Date(Math.floor(now.getTime() / policy.windowMs) * policy.windowMs); const expiresAt = new Date(windowStart.getTime() + policy.windowMs * 2); const keyHash = rateLimitKeyHash(scope, identifier || "unknown"); const rows = await database.$queryRaw<Array<{ count: number }>>`INSERT INTO "RateLimitBucket" ("id", "keyHash", "scope", "windowStart", "count", "expiresAt", "createdAt", "updatedAt") VALUES (${randomUUID()}, ${keyHash}, ${scope}::"RateLimitScope", ${windowStart}, 1, ${expiresAt}, NOW(), NOW()) ON CONFLICT ("keyHash", "scope", "windowStart") DO UPDATE SET "count" = "RateLimitBucket"."count" + 1, "updatedAt" = NOW() RETURNING "count"`; if (Math.random() < 0.01) await database.rateLimitBucket.deleteMany({ where: { expiresAt: { lt: now } } }); const count = rows[0]?.count ?? policy.limit + 1; return { allowed: count <= policy.limit, remaining: Math.max(0, policy.limit - count), retryAfterSeconds: Math.max(1, Math.ceil((windowStart.getTime() + policy.windowMs - now.getTime()) / 1000)) }; }
export async function clearRateLimit(scope: RateLimitScope, identifier: string) { await database.rateLimitBucket.deleteMany({ where: { scope, keyHash: rateLimitKeyHash(scope, identifier) } }); }
export async function cleanupExpiredRateLimits(now = new Date()) { return database.rateLimitBucket.deleteMany({ where: { expiresAt: { lt: now } } }); }
